name: Build LaTeX Document

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install TeX Live
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex

      - name: Compile LaTeX document
        run: pdflatex main.tex

      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: Compiled-PDF
          path: main.pdf
